"""花の画像を変更したら実行: python3 scripts/embed-flower.py"""
import base64
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
names = ('mv-image.webp', 'mv-image-mono.webp',
         'mv-image-sp.webp', 'mv-image-mono-sp.webp')
textures = {}
for name in names:
    path = 'images/home/' + name
    textures[path] = 'data:image/webp;base64,' + base64.b64encode(
        (root / path).read_bytes()).decode('ascii')

(root / 'js/flower-textures.js').write_text(
    '// Generated by scripts/embed-flower.py. Edit the source images, then regenerate.\n'
    + 'window.portfolioFlowerTextures = ' + json.dumps(textures) + ';\n',
    encoding='utf-8')
print('Embedded 4 flower textures.')
